### ISSUE TITLE
Possible Issue in AndroidX

### ISSUE THREAD

**Issue by saamerm** [AvantiPoint/AP.MobileToolkit#179]
Should this line say :
`#IF MonoAndroid90 || MonoAndroid10.0`

https://github.com/AvantiPoint/AP.MobileToolkit/blob/726fb74d318e1c4269b3fc592b6a6eecf291f3a8/src/Forms/AP.MobileToolkit.Forms/Controls/Platform/Droid/ImageEntryRenderer.cs#L50

**Comment by dansiegel** [comment]
I haven't looked at it in a while but I don't believe so. The file itself is compiled only for MonoAndroid 9.0 or 10.0 so there would be no reason for a compiler directive there with that condition. As I recall it's there due to a subtle difference in the 9.0 & 10.0 API's.

If you're having a specific issue please let me know.
